server:
  port: 3333
  
spring:
  cloud:
    gateway:
      discovery.locator:
       enabled: true
       lower-case-service-id: true
      routes:
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet
      - id: work-api
        uri: lb://WORK-API
        predicates:
        - Path=/work
  application:
    name: SPRING-CLOUD-GATEWAY
          
             
  