management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 9090
  
spring:
  application:
    name: WORK-API
  boot:
    admin:
      client:
        url: http://localhost:7777/
